name: Java Frontend CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compilar projeto
        run: |
          javac -d out src/*.java

      #- name: Rodar testes (se houver)
       # run: |
        #  java -cp out org.junit.runner.JUnitCore MeuTeste
